### ISSUE TITLE
Create 8.0.x branch to match d.o

### ISSUE THREAD

**Issue by damienmckenna** [stevector/search_api_pantheon#149]
PR #145 added the necessary to automatically push branches from github to d.o.

However, the changes aren't working as expected because on github the active branch is named "8.x" whereas on d.o it is named "8.0.x". As a comaintainer on d.o I had to manually merge the 8.x changes into 8.0.x so that anyone pulling the changes from the d.o dev snapshot had the latest code.

Could someone please create a new 8.0.x branch here on github and use it from now on? Thank you.

**Comment by kporras07** [comment]
Good catch. Thanks. Done

**Comment by kporras07** [comment]
Actually, I revisited this and made 8.x the default branch in d.o. so that it matches 8.x in Github and we can all forget about 8.0.x

**Comment by kporras07** [comment]
I just noticed there is a link to 8.0.x https://www.drupal.org/project/search_api_pantheon/releases/8.0.x-dev 

Do you know if there is a way of getting rid of it? Or we should stay on 8.0.x?

**Comment by kporras07** [comment]
I managed to remove the link and create 8.x-dev dev snapshot release.

I can't delete 8.0.x release and I'm not sure if deleting a branch in d.o. is possible/recommended. So I guess I could update the release notes from the link above and point people to 8.x to have a consolidated 8.x branch and start working on d10 compatibility stuff there.

I'll go with this plan later today/tomorrow unless there is any objection/better-recommended approach

**Comment by damienmckenna** [comment]
First off, you can't delete branches that have tagged releases on them.

Deleting the 8.0.x branch is the wrong approach. The correct approach would have been to rename the 8.x branch on github before someone tagged a release on it on d.o, but that mistake was done a few weeks ago.

This project should follow semantic versioning, i.e. 8.0.x to correspond to 8.0.3 etc releases, then 8.1.x to correspond to the 8.1.0 etc releases, then 8.2.x, etc. Having an 8.x branch and then tagging different releases off it using the 8.0.x or 8.1.x tags is the wrong way to do it.

Please adhere to semantic versioning on the branches in addition to the releases.

Thank you.
