### ISSUE TITLE
Scrap the new 9.x branch

### ISSUE THREAD

**Issue by damienmckenna** [stevector/search_api_pantheon#153]
There is zero reason to create a new branch in order to add D10 support.

Please see this excellent blog post on why the D10 changes should be committed to the existing 8.x branch:
https://medium.com/jakob-on-drupal/dont-go-making-major-version-changes-474293dda1d7

**Comment by kporras07** [comment]
Nice lecture. Thanks! Branch removed and we're ready to release 8.1.0 in d.o.

**Comment by damienmckenna** [comment]
Thank you for your understanding.
