### ISSUE TITLE
ArgumentCountError when posting schema

### ISSUE THREAD

**Issue by jms-pantheon** [stevector/search_api_pantheon#158]
**Describe the bug**
When trying to post default schema:

ArgumentCountError: Too few arguments to function Drupal\search_api_solr\Controller\SolrConfigSetController::__construct(), 0 passed in /code/web/modules/composer/search_api_pantheon/src/Services/SchemaPoster.php on line 245 and exactly 1 expected in Drupal\search_api_solr\Controller\SolrConfigSetController->__construct() (Zeile 52 in /code/web/modules/composer/search_api_solr/src/Controller/SolrConfigSetController.php)

**To Reproduce**
1. Submit form on: /admin/config/search/search-api/server/pantheon_solr8/pantheon-admin/schema

Says leave empty to use default, but gives above error.

**Additional context**
Using 8.1

A community patch solves this issue: 

https://www.drupal.org/project/search_api_pantheon/issues/3320326

**Comment by rwagner00** [comment]
An internal issue has been created to get the patch reviewed and merged, thank you!
