### ISSUE TITLE
Create 8.1.x branch for 8.1.x releases

### ISSUE THREAD

**Issue by damienmckenna** [stevector/search_api_pantheon#161]
The work that is tagged 8.1.0 etc should be on a branch named "8.1.x" rather than "8.x".

**Comment by namespacebrian** [comment]
Tracking internally as CMS-1192

**Comment by damienmckenna** [comment]
I forked the 8.x branch to create the 8.1.x branch and pushed it to d.o, please make the same changes on this repo.

**Comment by damienmckenna** [comment]
Bump. Can someone please take care of this? Thank you.

**Comment by scottbuscemi** [comment]
We've rolled out the automation to handle this now. Thank you for the report!
