### ISSUE TITLE
Error: Class 'RicardoFiorani\GuzzlePsr18Adapter\Client' not found

### ISSUE THREAD

**Issue by kyletaylored** [stevector/search_api_pantheon#83]
When adding a new server, this pops up.

```
Error: Class 'RicardoFiorani\GuzzlePsr18Adapter\Client' not found in Drupal\search_api_pantheon\Utility\SolrGuzzle::getConfiguredClientInterface() (line 35 of /code/modules/contrib/search_api_pantheon/src/Utility/SolrGuzzle.php)
```

**Comment by kyletaylored** [comment]
This looks like it's due to how I'm loading it into a site via Composer. It's not installing the dependencies listed, it's just plopping it into the modules directory without installing anything else. Will look into this.

**Comment by stovak** [comment]
Did you resolve this? it's in the module composer.json?

**Comment by kyletaylored** [comment]
This actually worked for me. Would recommend others using this to install and test in EA.

```
composer config repositories.search_api_pantheon vcs git@github.com:pantheon-systems/search_api_pantheon.git
composer require drupal/search_api_pantheon:"dev-8.x-8.x"
```

**Comment by stovak** [comment]
`composer require pantheon-systems/search-api-pantheon` now works.
