### ISSUE TITLE
ParseError: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by kyletaylored** [stevector/search_api_pantheon#84]
When adding a new server. It's actually `?object` as one of the class properties, seems like a typo.

> ```ParseError: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in Symfony\Component\ClassLoader\ApcClassLoader->loadClass() (line 53 of /code/modules/contrib/search_api_pantheon/src/Plugin/SolrConnector/PantheonSolrConnector.php)```

**Comment by kyletaylored** [comment]
Oh, I see this is a type declaration. This seems to break on PHP 7.3... Will try on 7.4

**Comment by kyletaylored** [comment]
Follow-up error after upgrade to PHP 7.4

> ``` Fatal error: Type of Drupal\search_api_pantheon\Plugin\SolrConnector\PantheonSolrConnector::$eventDispatcher must not be defined (as in class Drupal\search_api_solr\SolrConnector\SolrConnectorPluginBase) in /code/modules/contrib/search_api_pantheon/src/Plugin/SolrConnector/PantheonSolrConnector.php on line 44```

**Comment by stovak** [comment]
ok, I'm using 8. Will revert to 7.4 and test.

**Comment by stovak** [comment]
Fixed with next push.
